name: Generate Snake Animation

on:
  schedule: # Runs at 23:59 UTC every day
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: .github/contribution-grid-snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
